name: auth_lorby
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_bloc: ^8.1.4
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4


#flutter_native_splash:
 
  #background_image: assets/splash.png
  
#  android: true
 # ios: true
  #web: false
 # android_12:
  
    #background_image: assets/splash.png

  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: MPlusRegular
      fonts:
        - asset: fonts/mplus_regular.ttf

  # To add assets to your application, add an assets section, like this:
